application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      simpleApp:
        license: Apache-2.0
        actions:
          hello:
            function: actions/hello/index.js
            web: 'yes'
            inputs:
              TEST_VAR_MODIFIED: $TEST_VAR
              TEST_VAR_DEFINED: 'Hello World Action Variable'
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
          save-user:
            function: actions/users/save.js
            web: 'yes'
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
          list-users:
            function: actions/users/list.js
            web: 'yes'
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
          delete-user:
            function: actions/users/delete.js
            web: 'yes'
            runtime: nodejs:22
            annotations:
              require-adobe-auth: true
extensions:
  commerce/backend-ui/1:
    $include: ./ext.config.yaml  
